var monedaCatalogue = {
  { code: 'AED', description: 'Dirham de EAU' },
  { code: 'AFN', description: 'Afghani' },
  { code: 'ALL', description: 'Lek' },
  { code: 'AMD', description: 'Dram armenio' },
  { code: 'ANG', description: 'Florín antillano neerlandés' },
  { code: 'AOA', description: 'Kwanza' },
  { code: 'ARS', description: 'Peso Argentino' },
  { code: 'AUD', description: 'Dólar Australiano' },
  { code: 'AWG', description: 'Aruba Florin' },
  { code: 'AZN', description: 'Azerbaijanian Manat' },
  { code: 'BAM', description: 'Convertibles marca' },
  { code: 'BBD', description: 'Dólar de Barbados' },
  { code: 'BDT', description: 'Taka' },
  { code: 'BGN', description: 'Lev búlgaro' },
  { code: 'BHD', description: 'Dinar de Bahrein' },
  { code: 'BIF', description: 'Burundi Franc' },
  { code: 'BMD', description: 'Dólar de Bermudas' },
  { code: 'BND', description: 'Dólar de Brunei' },
  { code: 'BOB', description: 'Boliviano' },
  { code: 'BOV', description: 'Mvdol' },
  { code: 'BRL', description: 'Real brasileño' },
  { code: 'BSD', description: 'Dólar de las Bahamas' },
  { code: 'BTN', description: 'Ngultrum' },
  { code: 'BWP', description: 'Pula' },
  { code: 'BYR', description: 'Rublo bielorruso' },
  { code: 'BZD', description: 'Dólar de Belice' },
  { code: 'CAD', description: 'Dolar Canadiense' },
  { code: 'CDF', description: 'Franco congoleño' },
  { code: 'CHE', description: 'WIR Euro' },
  { code: 'CHF', description: 'Franco Suizo' },
  { code: 'CHW', description: 'Franc WIR' },
  { code: 'CLF', description: 'Unidad de Fomento' },
  { code: 'CLP', description: 'Peso chileno' },
  { code: 'CNY', description: 'Yuan Renminbi' },
  { code: 'COP', description: 'Peso Colombiano' },
  { code: 'COU', description: 'Unidad de Valor real' },
  { code: 'CRC', description: 'Colón costarricense' },
  { code: 'CUC', description: 'Peso Convertible' },
  { code: 'CUP', description: 'Peso Cubano' },
  { code: 'CVE', description: 'Cabo Verde Escudo' },
  { code: 'CZK', description: 'Corona checa' },
  { code: 'DJF', description: 'Franco de Djibouti' },
  { code: 'DKK', description: 'Corona danesa' },
  { code: 'DOP', description: 'Peso Dominicano' },
  { code: 'DZD', description: 'Dinar argelino' },
  { code: 'EGP', description: 'Libra egipcia' },
  { code: 'ERN', description: 'Nakfa' },
  { code: 'ETB', description: 'Birr etíope' },
  { code: 'EUR', description: 'Euro' },
  { code: 'FJD', description: 'Dólar de Fiji' },
  { code: 'FKP', description: 'Libra malvinense' },
  { code: 'GBP', description: 'Libra Esterlina' },
  { code: 'GEL', description: 'Lari' },
  { code: 'GHS', description: 'Cedi de Ghana' },
  { code: 'GIP', description: 'Libra de Gibraltar' },
  { code: 'GMD', description: 'Dalasi' },
  { code: 'GNF', description: 'Franco guineano' },
  { code: 'GTQ', description: 'Quetzal' },
  { code: 'GYD', description: 'Dólar guyanés' },
  { code: 'HKD', description: 'Dolar De Hong Kong' },
  { code: 'HNL', description: 'Lempira' },
  { code: 'HRK', description: 'Kuna' },
  { code: 'HTG', description: 'Gourde' },
  { code: 'HUF', description: 'Florín' },
  { code: 'IDR', description: 'Rupia' },
  { code: 'ILS', description: 'Nuevo Shekel Israelí' },
  { code: 'INR', description: 'Rupia india' },
  { code: 'IQD', description: 'Dinar iraquí' },
  { code: 'IRR', description: 'Rial iraní' },
  { code: 'ISK', description: 'Corona islandesa' },
  { code: 'JMD', description: 'Dólar Jamaiquino' },
  { code: 'JOD', description: 'Dinar jordano' },
  { code: 'JPY', description: 'Yen' },
  { code: 'KES', description: 'Chelín keniano' },
  { code: 'KGS', description: 'Som' },
  { code: 'KHR', description: 'Riel' },
  { code: 'KMF', description: 'Franco Comoro' },
  { code: 'KPW', description: 'Corea del Norte ganó' },
  { code: 'KRW', description: 'Won' },
  { code: 'KWD', description: 'Dinar kuwaití' },
  { code: 'KYD', description: 'Dólar de las Islas Caimán' },
  { code: 'KZT', description: 'Tenge' },
  { code: 'LAK', description: 'Kip' },
  { code: 'LBP', description: 'Libra libanesa' },
  { code: 'LKR', description: 'Rupia de Sri Lanka' },
  { code: 'LRD', description: 'Dólar liberiano' },
  { code: 'LSL', description: 'Loti' },
  { code: 'LYD', description: 'Dinar libio' },
  { code: 'MAD', description: 'Dirham marroquí' },
  { code: 'MDL', description: 'Leu moldavo' },
  { code: 'MGA', description: 'Ariary malgache' },
  { code: 'MKD', description: 'Denar' },
  { code: 'MMK', description: 'Kyat' },
  { code: 'MNT', description: 'Tugrik' },
  { code: 'MOP', description: 'Pataca' },
  { code: 'MRO', description: 'Ouguiya' },
  { code: 'MUR', description: 'Rupia de Mauricio' },
  { code: 'MVR', description: 'Rupia' },
  { code: 'MWK', description: 'Kwacha' },
  { code: 'MXN', description: 'Peso Mexicano' },
  { code: 'MXV', description: 'México Unidad de Inversión (UDI)' },
  { code: 'MYR', description: 'Ringgit malayo' },
  { code: 'MZN', description: 'Mozambique Metical' },
  { code: 'NAD', description: 'Dólar de Namibia' },
  { code: 'NGN', description: 'Naira' },
  { code: 'NIO', description: 'Córdoba Oro' },
  { code: 'NOK', description: 'Corona noruega' },
  { code: 'NPR', description: 'Rupia nepalí' },
  { code: 'NZD', description: 'Dólar de Nueva Zelanda' },
  { code: 'OMR', description: 'Rial omaní' },
  { code: 'PAB', description: 'Balboa' },
  { code: 'PEN', description: 'Nuevo Sol' },
  { code: 'PGK', description: 'Kina' },
  { code: 'PHP', description: 'Peso filipino' },
  { code: 'PKR', description: 'Rupia de Pakistán' },
  { code: 'PLN', description: 'Zloty' },
  { code: 'PYG', description: 'Guaraní' },
  { code: 'QAR', description: 'Qatar Rial' },
  { code: 'RON', description: 'Leu rumano' },
  { code: 'RSD', description: 'Dinar serbio' },
  { code: 'RUB', description: 'Rublo ruso' },
  { code: 'RWF', description: 'Franco ruandés' },
  { code: 'SAR', description: 'Riyal saudí' },
  { code: 'SBD', description: 'Dólar de las Islas Salomón' },
  { code: 'SCR', description: 'Rupia de Seychelles' },
  { code: 'SDG', description: 'Libra sudanesa' },
  { code: 'SEK', description: 'Corona sueca' },
  { code: 'SGD', description: 'Dolar De Singapur' },
  { code: 'SHP', description: 'Libra de Santa Helena' },
  { code: 'SLL', description: 'Leona' },
  { code: 'SOS', description: 'Chelín somalí' },
  { code: 'SRD', description: 'Dólar de Suriname' },
  { code: 'SSP', description: 'Libra sudanesa Sur' },
  { code: 'STD', description: 'Dobra' },
  { code: 'SVC', description: 'Colon El Salvador' },
  { code: 'SYP', description: 'Libra Siria' },
  { code: 'SZL', description: 'Lilangeni' },
  { code: 'THB', description: 'Baht' },
  { code: 'TJS', description: 'Somoni' },
  { code: 'TMT', description: 'Turkmenistán nuevo manat' },
  { code: 'TND', description: 'Dinar tunecino' },
  { code: 'TOP', description: 'Pa\'anga' },
  { code: 'TRY', description: 'Lira turca' },
  { code: 'TTD', description: 'Dólar de Trinidad y Tobago' },
  { code: 'TWD', description: 'Nuevo dólar de Taiwán' },
  { code: 'TZS', description: 'Shilling tanzano' },
  { code: 'UAH', description: 'Hryvnia' },
  { code: 'UGX', description: 'Shilling de Uganda' },
  { code: 'USD', description: 'Dolar americano' },
  { code: 'USN', description: 'Dólar estadounidense (día siguiente)' },
  { code: 'UYI', description: 'Peso Uruguay en Unidades Indexadas (URUIURUI)' },
  { code: 'UYU', description: 'Peso Uruguayo' },
  { code: 'UZS', description: 'Uzbekistán Sum' },
  { code: 'VEF', description: 'Bolívar' },
  { code: 'VND', description: 'Dong' },
  { code: 'VUV', description: 'Vatu' },
  { code: 'WST', description: 'Tala' },
  { code: 'XAF', description: 'Franco CFA BEAC' },
  { code: 'XAG', description: 'Plata' },
  { code: 'XAU', description: 'Oro' },
  { code: 'XBA', description: 'Unidad de Mercados de Bonos Unidad Europea Composite (EURCO)' },
  { code: 'XBB', description: 'Unidad Monetaria de Bonos de Mercados Unidad Europea (UEM-6)' },
  { code: 'XBC', description: 'Mercados de Bonos Unidad Europea unidad de cuenta a 9 (UCE-9)' },
  { code: 'XBD', description: 'Mercados de Bonos Unidad Europea unidad de cuenta a 17 (UCE-17)' },
  { code: 'XCD', description: 'Dólar del Caribe Oriental' },
  { code: 'XDR', description: 'DEG (Derechos Especiales de Giro)' },
  { code: 'XOF', description: 'Franco CFA BCEAO' },
  { code: 'XPD', description: 'Paladio' },
  { code: 'XPF', description: 'Franco CFP' },
  { code: 'XPT', description: 'Platino' },
  { code: 'XSU', description: 'Sucre' },
  { code: 'XTS', description: 'Códigos reservados específicamente para propósitos de prueba' },
  { code: 'XUA', description: 'Unidad ADB de Cuenta' },
  { code: 'XXX', description: 'Los códigos asignados para las transacciones en que intervenga ninguna moneda' },
  { code: 'YER', description: 'Rial yemení' },
  { code: 'ZAR', description: 'Rand' },
  { code: 'ZMW', description: 'Kwacha zambiano' },
  { code: 'ZWL', description: 'Zimbabwe Dólar' }
}

module.exports = monedaCatalogue
